//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 08:15:45 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.companyInfoSchema.net", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package company.db;
